# Generated by Django 2.1.2 on 2018-11-17 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentdetail',
            name='blood_type',
            field=models.CharField(choices=[('A+', 'A Positive'), ('A-', 'A Negative'), ('B+', 'B Positive'), ('B-', 'B Negative'), ('O+', 'O Positive'), ('O-', 'O Negative'), ('AB+', 'AB Positive'), ('AB-', 'AB Negative')], max_length=100),
        ),
        migrations.AlterField(
            model_name='paymentdetail',
            name='prescription',
            field=models.ImageField(default='default.jpg', upload_to='prescription'),
        ),
    ]
