# Generated by Django 2.1 on 2018-11-25 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_donordetail_donate_complete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donordetail',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Donor_reg'),
        ),
        migrations.AlterField(
            model_name='hospitaldetail',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Hospital_reg'),
        ),
        migrations.AlterField(
            model_name='patientdetail',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Patient_reg'),
        ),
    ]
