# Generated by Django 2.1.2 on 2018-11-17 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='paymentDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_type', models.CharField(max_length=100)),
                ('units', models.IntegerField(default=0)),
                ('address', models.TextField()),
                ('prescription', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('order_complete', models.BooleanField(default=False)),
            ],
        ),
    ]
