# Generated by Django 2.1.2 on 2018-12-11 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donor_portal', '0002_auto_20181211_2245'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='finaldonation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('units', models.CharField(blank=True, choices=[('1', '1'), ('2', '2')], max_length=2)),
                ('donation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='donor_portal.Donor_DataBase')),
            ],
        ),
    ]
