# Generated by Django 2.1.2 on 2018-11-18 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_auto_20181118_0119'),
    ]

    operations = [
        migrations.CreateModel(
            name='finalorder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component', models.CharField(choices=[('RBCLs', 'Red Blood Cells'), ('Plasmas', 'Plasma'), ('Platelets', 'Platelets')], max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='paymentdetail',
            name='prescription',
            field=models.ImageField(default='prescription/default.jpg', upload_to='prescription/'),
        ),
        migrations.AddField(
            model_name='finalorder',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='payments.paymentDetail'),
        ),
    ]
