# Generated by Django 2.1.2 on 2018-11-18 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_auto_20181118_1707'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finalorder',
            name='order',
        ),
    ]
