# Generated by Django 2.1.2 on 2018-11-25 09:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '__first__'),
        ('payments', '0006_finalorder_order_complete'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diseases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Asthma', models.BooleanField(default=False)),
                ('Cancer', models.BooleanField(default=False)),
                ('Cardiac_Disease', models.BooleanField(default=False)),
                ('Diabetes', models.BooleanField(default=False)),
                ('Hypertension', models.BooleanField(default=False)),
                ('Pyschiatric_Disorder', models.BooleanField(default=False)),
                ('Epilepsy', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='donorDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.Donor_reg')),
            ],
        ),
        migrations.CreateModel(
            name='hospitalDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_type', models.CharField(choices=[('A+', 'A Positive'), ('A-', 'A Negative'), ('B+', 'B Positive'), ('B-', 'B Negative'), ('O+', 'O Positive'), ('O-', 'O Negative'), ('AB+', 'AB Positive'), ('AB-', 'AB Negative')], max_length=100)),
                ('units', models.IntegerField(default=0)),
                ('component', models.CharField(blank=True, choices=[('RBCLs', 'Red Blood Cells'), ('Plasmas', 'Plasma'), ('Platelets', 'Platelets')], max_length=100)),
                ('order_complete', models.BooleanField(default=False)),
                ('date_ordered', models.DateTimeField(default=django.utils.timezone.now)),
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.Hospital_reg')),
            ],
        ),
        migrations.CreateModel(
            name='patientDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_type', models.CharField(choices=[('A+', 'A Positive'), ('A-', 'A Negative'), ('B+', 'B Positive'), ('B-', 'B Negative'), ('O+', 'O Positive'), ('O-', 'O Negative'), ('AB+', 'AB Positive'), ('AB-', 'AB Negative')], max_length=100)),
                ('units', models.IntegerField(default=0)),
                ('prescription', models.ImageField(default='payments/default.jpg', upload_to='payments/')),
                ('order_complete', models.BooleanField(default=False)),
                ('date_ordered', models.DateTimeField(default=django.utils.timezone.now)),
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.Patient_reg')),
            ],
        ),
        migrations.DeleteModel(
            name='paymentDetail',
        ),
        migrations.AlterField(
            model_name='finalorder',
            name='component',
            field=models.CharField(blank=True, choices=[('RBCLs', 'Red Blood Cells'), ('Plasmas', 'Plasma'), ('Platelets', 'Platelets')], max_length=100),
        ),
        migrations.AddField(
            model_name='diseases',
            name='donor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='payments.donorDetail'),
        ),
    ]
