# Generated by Django 2.1.2 on 2018-11-25 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_auto_20181125_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='donordetail',
            name='donate_complete',
            field=models.BooleanField(default=False),
        ),
    ]
