# Generated by Django 2.1.2 on 2018-12-11 14:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diseases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Asthma', models.CharField(default='No', max_length=3)),
                ('Cancer', models.CharField(default='No', max_length=3)),
                ('Cardiac_Disease', models.CharField(default='No', max_length=3)),
                ('Diabetes', models.CharField(default='No', max_length=3)),
                ('Hypertension', models.CharField(default='No', max_length=3)),
                ('Kidney_Disease', models.CharField(default='No', max_length=3)),
                ('Epilepsy', models.CharField(default='No', max_length=3)),
                ('HIV', models.CharField(default='No', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Donor_DataBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_units', models.IntegerField(default=1)),
                ('don_or_sell', models.CharField(max_length=6)),
                ('last_donate_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('donation_complete', models.BooleanField(default=False)),
                ('user_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.Donor_reg')),
            ],
        ),
        migrations.AddField(
            model_name='diseases',
            name='donor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='donor_portal.Donor_DataBase'),
        ),
    ]
