# Generated by Django 2.1.2 on 2018-12-11 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor_portal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donor_database',
            name='blood_units',
        ),
        migrations.AlterField(
            model_name='donor_database',
            name='don_or_sell',
            field=models.CharField(max_length=10),
        ),
    ]
