# Generated by Django 2.1.2 on 2018-11-17 12:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='frozen_cryo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_type', models.CharField(choices=[('A+', 'A Positive'), ('A-', 'A Negative'), ('B+', 'B Positive'), ('B-', 'B Negative'), ('O+', 'O Positive'), ('O-', 'O Negative'), ('AB+', 'AB Positive'), ('AB-', 'AB Negative')], max_length=100)),
                ('units', models.IntegerField(default=0)),
                ('donate_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('time_left', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Frozen_Cryos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_type', models.CharField(choices=[('A+', 'A Positive'), ('A-', 'A Negative'), ('B+', 'B Positive'), ('B-', 'B Negative'), ('O+', 'O Positive'), ('O-', 'O Negative'), ('AB+', 'AB Positive'), ('AB-', 'AB Negative')], max_length=100)),
                ('current_inv', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Plasma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_type', models.CharField(choices=[('O', 'O'), ('A', 'A'), ('B', 'B'), ('AB', 'AB')], max_length=100)),
                ('units', models.IntegerField(default=0)),
                ('donate_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('time_left', models.FloatField(default=0)),
                ('expiry', models.IntegerField(default=100)),
            ],
        ),
        migrations.CreateModel(
            name='Plasmas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_type', models.CharField(choices=[('O', 'O'), ('A', 'A'), ('B', 'B'), ('AB', 'AB')], max_length=100)),
                ('price', models.IntegerField()),
                ('current_inv', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Platelet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('units', models.IntegerField(default=0)),
                ('donate_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('time_left', models.FloatField(default=0)),
                ('expiry', models.IntegerField(default=120)),
            ],
        ),
        migrations.CreateModel(
            name='Platelets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('current_inv', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='RBCL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_type', models.CharField(choices=[('A+', 'A Positive'), ('A-', 'A Negative'), ('B+', 'B Positive'), ('B-', 'B Negative'), ('O+', 'O Positive'), ('O-', 'O Negative'), ('AB+', 'AB Positive'), ('AB-', 'AB Negative')], max_length=100)),
                ('units', models.IntegerField(default=0)),
                ('donate_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('time_left', models.FloatField(default=0)),
                ('expiry', models.IntegerField(default=1010)),
            ],
        ),
        migrations.CreateModel(
            name='RBCLs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_type', models.CharField(choices=[('A+', 'A Positive'), ('A-', 'A Negative'), ('B+', 'B Positive'), ('B-', 'B Negative'), ('O+', 'O Positive'), ('O-', 'O Negative'), ('AB+', 'AB Positive'), ('AB-', 'AB Negative')], max_length=100)),
                ('price', models.IntegerField()),
                ('current_inv', models.IntegerField(default=0)),
            ],
        ),
    ]
