# Generated by Django 2.1.2 on 2018-11-11 07:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('InventoryManagement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plasma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_type', models.CharField(choices=[('O', 'O'), ('A', 'A'), ('B', 'B'), ('AB', 'AB')], max_length=100)),
                ('donate_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('units', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Platelets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donate_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('units', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='RBCL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_type', models.CharField(choices=[('A+', 'A Positive'), ('A-', 'A Negative'), ('B+', 'A Positive'), ('B-', 'A Negative'), ('O+', 'A Positive'), ('O-', 'A Negative'), ('AB+', 'A Positive'), ('AB-', 'A Negative')], max_length=100)),
                ('donate_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('units', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='Inventory',
        ),
    ]
