# Generated by Django 2.1.2 on 2018-11-18 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InventoryManagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plasma',
            name='time_left',
            field=models.FloatField(default=100),
        ),
        migrations.AlterField(
            model_name='platelet',
            name='time_left',
            field=models.FloatField(default=120),
        ),
        migrations.AlterField(
            model_name='rbcl',
            name='time_left',
            field=models.FloatField(default=1010),
        ),
    ]
