# Generated by Django 2.1.2 on 2018-11-11 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InventoryManagement', '0002_auto_20181111_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rbcl',
            name='blood_type',
            field=models.CharField(choices=[('A+', 'A Positive'), ('A-', 'A Negative'), ('B+', 'B Positive'), ('B-', 'B Negative'), ('O+', 'O Positive'), ('O-', 'O Negative'), ('AB+', 'AB Positive'), ('AB-', 'AB Negative')], max_length=100),
        ),
    ]
