# Generated by Django 2.1.2 on 2018-11-11 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InventoryManagement', '0003_auto_20181111_1245'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Platelets',
            new_name='Platelet',
        ),
    ]
