# Generated by Django 2.1.2 on 2018-11-11 13:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('InventoryManagement', '0004_auto_20181111_1533'),
    ]

    operations = [
        migrations.CreateModel(
            name='frozen_cryo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_type', models.CharField(choices=[('A+', 'A Positive'), ('A-', 'A Negative'), ('B+', 'B Positive'), ('B-', 'B Negative'), ('O+', 'O Positive'), ('O-', 'O Negative'), ('AB+', 'AB Positive'), ('AB-', 'AB Negative')], max_length=100)),
                ('donate_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('units', models.IntegerField(default=0)),
            ],
        ),
    ]
