# Generated by Django 2.1.2 on 2018-11-12 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InventoryManagement', '0005_frozen_cryo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Frozen_Cryos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_type', models.CharField(choices=[('A+', 'A Positive'), ('A-', 'A Negative'), ('B+', 'B Positive'), ('B-', 'B Negative'), ('O+', 'O Positive'), ('O-', 'O Negative'), ('AB+', 'AB Positive'), ('AB-', 'AB Negative')], max_length=100)),
                ('current_inv', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Plasmas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_type', models.CharField(choices=[('O', 'O'), ('A', 'A'), ('B', 'B'), ('AB', 'AB')], max_length=100)),
                ('price', models.IntegerField()),
                ('current_inv', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Platelets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('current_inv', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='RBCLs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_type', models.CharField(choices=[('A+', 'A Positive'), ('A-', 'A Negative'), ('B+', 'B Positive'), ('B-', 'B Negative'), ('O+', 'O Positive'), ('O-', 'O Negative'), ('AB+', 'AB Positive'), ('AB-', 'AB Negative')], max_length=100)),
                ('price', models.IntegerField()),
                ('current_inv', models.IntegerField(default=0)),
            ],
        ),
    ]
