# Generated by Django 2.1.2 on 2018-11-14 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InventoryManagement', '0006_frozen_cryos_plasmas_platelets_rbcls'),
    ]

    operations = [
        migrations.AddField(
            model_name='frozen_cryo',
            name='time_passed',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='plasma',
            name='time_passed',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='platelet',
            name='time_passed',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='rbcl',
            name='time_passed',
            field=models.FloatField(default=0),
        ),
    ]
