# Generated by Django 2.1.2 on 2018-11-14 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InventoryManagement', '0007_auto_20181114_2230'),
    ]

    operations = [
        migrations.AddField(
            model_name='plasma',
            name='expiry',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='platelet',
            name='expiry',
            field=models.IntegerField(default=120),
        ),
        migrations.AddField(
            model_name='rbcl',
            name='expiry',
            field=models.IntegerField(default=1010),
        ),
    ]
