# Generated by Django 2.1.2 on 2018-11-14 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InventoryManagement', '0008_auto_20181115_0036'),
    ]

    operations = [
        migrations.RenameField(
            model_name='frozen_cryo',
            old_name='time_passed',
            new_name='time_left',
        ),
        migrations.RenameField(
            model_name='plasma',
            old_name='time_passed',
            new_name='time_left',
        ),
        migrations.RenameField(
            model_name='platelet',
            old_name='time_passed',
            new_name='time_left',
        ),
        migrations.RenameField(
            model_name='rbcl',
            old_name='time_passed',
            new_name='time_left',
        ),
    ]
