# Generated by Django 2.1 on 2018-11-18 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InventoryManagement', '0002_auto_20181118_1248'),
        ('InventoryManagement', '0009_auto_20181115_0039'),
    ]

    operations = [
    ]
