# Generated by Django 2.1.2 on 2018-10-08 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('user_name', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=20)),
                ('blood_group', models.CharField(max_length=3)),
            ],
        ),
    ]
