# Generated by Django 2.1 on 2018-10-14 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='donors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, null=True)),
                ('email', models.CharField(max_length=50)),
                ('uname', models.CharField(max_length=50)),
                ('passwd', models.CharField(max_length=30)),
                ('dob', models.DateField()),
                ('line1', models.CharField(max_length=150)),
                ('line2', models.CharField(max_length=150)),
                ('postalcode', models.CharField(max_length=6)),
                ('city', models.CharField(max_length=150)),
                ('country', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='hospital',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, null=True)),
                ('email', models.CharField(max_length=50)),
                ('uname', models.CharField(max_length=50)),
                ('passwd', models.CharField(max_length=30)),
                ('license', models.CharField(max_length=30)),
                ('l_exp', models.DateField()),
                ('line1', models.CharField(max_length=150)),
                ('line2', models.CharField(max_length=150)),
                ('postalcode', models.CharField(max_length=6)),
                ('city', models.CharField(max_length=150)),
                ('country', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, null=True)),
                ('email', models.CharField(max_length=50)),
                ('uname', models.CharField(max_length=50)),
                ('passwd', models.CharField(max_length=30)),
                ('dob', models.DateField()),
            ],
        ),
    ]
