# Generated by Django 2.1 on 2018-12-06 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_hospital_reg_email_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospital_reg',
            name='email_verified',
        ),
    ]
