# Generated by Django 2.1 on 2018-12-06 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_hospital_reg_email_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital_reg',
            name='email_verified',
            field=models.IntegerField(null=True),
        ),
    ]
