# Generated by Django 2.1 on 2018-12-08 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_hospital_reg_email_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor_details',
            name='blood_group',
            field=models.CharField(choices=[('O', 'O+'), ('o', 'O-'), ('A', 'A+'), ('a', 'A-'), ('B', 'B+'), ('b', 'B-'), ('C', 'AB+'), ('c', 'AB-')], max_length=3),
        ),
        migrations.AlterField(
            model_name='donor_details',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1),
        ),
        migrations.AlterField(
            model_name='patient_details',
            name='blood_group',
            field=models.CharField(choices=[('O', 'O+'), ('o', 'O-'), ('A', 'A+'), ('a', 'A-'), ('B', 'B+'), ('b', 'B-'), ('C', 'AB+'), ('c', 'AB-')], max_length=3),
        ),
        migrations.AlterField(
            model_name='patient_details',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1),
        ),
    ]
