# Generated by Django 2.1 on 2018-11-11 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20181108_1458'),
    ]

    operations = [
        migrations.CreateModel(
            name='emconfirm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=50)),
                ('code', models.IntegerField()),
            ],
        ),
    ]
