# Generated by Django 2.1 on 2018-11-11 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20181111_1256'),
    ]

    operations = [
        migrations.CreateModel(
            name='cfm_em_code',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ab', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='temp_db',
        ),
    ]
