# Generated by Django 2.1 on 2018-11-11 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20181111_1314'),
    ]

    operations = [
        migrations.CreateModel(
            name='veremail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ab', models.IntegerField()),
                ('uname', models.CharField(max_length=50)),
            ],
        ),
    ]
