# Generated by Django 2.1 on 2018-11-11 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_veremail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='cfm_em_code',
        ),
        migrations.DeleteModel(
            name='emconfirm',
        ),
    ]
