# Generated by Django 2.1 on 2018-11-12 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20181112_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor_details',
            name='email_verified',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='hospital_reg',
            name='email_verified',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='patient_details',
            name='email_verified',
            field=models.IntegerField(null=True),
        ),
    ]
