# Generated by Django 2.1 on 2018-11-12 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20181112_1532'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donor_details',
            name='email_verified',
        ),
        migrations.RemoveField(
            model_name='hospital_reg',
            name='email_verified',
        ),
        migrations.RemoveField(
            model_name='patient_details',
            name='email_verified',
        ),
        migrations.AddField(
            model_name='donor_reg',
            name='email_verified',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='patient_reg',
            name='email_verified',
            field=models.IntegerField(null=True),
        ),
    ]
