# Generated by Django 2.1 on 2018-11-12 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20181112_1756'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient_details',
            old_name='user',
            new_name='userp',
        ),
    ]
