# Generated by Django 2.1.2 on 2018-12-11 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(default='default.jpg', upload_to='images/')),
                ('blood_units', models.IntegerField(default='0')),
                ('blood_group', models.CharField(max_length=11)),
                ('to_time', models.TimeField(blank=True, null=True)),
                ('from_time', models.TimeField(blank=True, null=True)),
                ('order_complete', models.BooleanField(default=False)),
                ('auth_complete', models.BooleanField(default=False)),
                ('user_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.Patient_reg')),
            ],
        ),
    ]
